site_name: mbedHandbooks

pages:

- ['README.md', 'Introduction to the Handbooks']
- ['v2/Intro.md', 'v2', 'Introduction to Version 2']
- ['v2/1_Getting_Started/1_Intro.md', 'Getting Started', 'Intro to mbed']
- ['v2/1_Getting_Started/2_Plat_Comp_Intro.md', 'Getting Started','Platforms and Components']
- ['v2/1_Getting_Started/3_User_Plat_Reg','Getting Started', 'Platform Registration']
- ['v2/1_Getting_Started/4_IDE_APImd','Getting Started', 'The IDE and API']
- ['v2/1_Getting_Started/5_First_Pro.md', 'Getting Started','First Program']
- ['v2/2_DEV_Fun/1_Intro.md', 'Development Fundamentals', 'Intro to Development Fundamentals']
- ['v2/2_DEV_Fun/2_API_Libs.md', 'Development Fundamentals','The APIs']
- ['v2/2_DEV_Fun/3_old_SDK.md','Development Fundamentals', 'The SDK (old)']
- ['v2/2_DEV_Fun/3_SDK.md', 'Development Fundamentals','The SDK']
- ['v2/2_DEV_Fun/4_HDK.md', 'Development Fundamentals','The HDK']
- ['v2/3_Adv_Dev/1_Intro.md','Advanced Development', 'Advanced Development on mbed']
- ['v2/3_Adv_Dev/2_Write_Publish.md','Advanced Development','Writing and Publishing Code']
- ['v2/3_Adv_Dev/3_Deug.md','Advanced Development','Debugging Code']
- ['v2/3_Adv_Dev/4_Docu.md','Advanced Development','Documenting Code']
- ['v2/3_Adv_Dev/5_Export.md','Advanced Development','Exporting Code']
- ['v2/4_Community/Intro.md','The mbed Community','The mbed Community']
- ['v2/4_Community/2_Questions.md','The mbed Community','Where to Ask Questions']
- ['v2/4_Community/3_Cont_SDK_HDK.md','The mbed Community','Cont SDK HDK']
- ['v2/4_Community/4_Edu','The mbed Community','Education']