site_name: mbed v2 Handbook

pages:
- ['index.md','Introduction to Version 2']
- ['Getting_Started/Intro.md','Introduction', 'Intro to mbed']
- ['Getting_Started/Plat_Comp_Intro.md','Introduction','Platforms and Components']
- ['Getting_Started/Rapid_Prototyping.md','Introduction','Rapid Prototyping']
- ['Getting_Started/IDE_API.md','Introduction','The IDE and API']
- ['Dev_Fun/SDK.md','Introduction','The SDK']
- ['Dev_Fun/HDK.md','Introduction','The HDK']
- ['Dev_Fun/API_Libs.md','Introduction','The APIs']
- ['Getting_Started/How_mbed_Works.md','Introduction','How mbed Works']
- ['Getting_Started/mbed_Interface.md','Introduction','The mbed Interface']
- ['Getting_Started/User_Plat_Reg.md','Getting Started','User and Platform Registration']
- ['Getting_Started/Using_IDE.md','Getting Started','Using the Compiler']
- ['Getting_Started/IDE_Shortcuts.md','Getting Started','Compiler Keyboard Shortcuts']
- ['Getting_Started/First_Pro.md','Getting Started','First Program']
- ['Community/Questions.md','Getting Started','Getting Help']
- ['Dev_Fun/Intro.md','Development on mbed','Intro to Development Fundamentals']
- ['Dev_Fun/API_Libs_Breakdown.md', 'Development on mbed','API Breakdown']
- ['Adv_Dev/PC_Com.md','Development on mbed','PC Serial Communication']
- ['Adv_Dev/Write_Publish.md','Development on mbed','Writing and Publishing Code']
- ['Adv_Dev/Debug.md','Development on mbed','Debugging Code']
- ['Adv_Dev/Coding_Style.md','Going Further','Coding Style Guide']
- ['Adv_Dev/Docu.md','Going Further','API Documentation']
- ['Adv_Dev/Export.md','Going Further','Exporting to Offline Toolchains']
- ['Adv_Dev/Lib_Internals.md','Going Further','Library Internals']
- ['Adv_Dev/Tools.md','Going Further','mbed Tools']
- ['Adv_Dev/Comp_Ver_Cont.md','Going Further','Compiler Version Control']
- ['Adv_Dev/SDK_Porting.md','Going Further','SDK Porting']
- ['Adv_Dev/Terminals.md','Going Further','Terminals']
- ['Adv_Dev/Serial.md','Going Further','The Serial Protocol']
- ['Adv_Dev/Serial_Conf.md','Going Further','Windows Serial Configuration']
- ['Adv_Dev/Mem_Mo.md','Going Further','The mbed Memory Model']
- ['Adv_Dev/RTOS_Mem.md','Going Further','The RTOS Memory Model']
- ['Dev_Fun/CMSIS.md','CMSIS','The CMSIS-DAP']
- ['Adv_Dev/CMSIS-DAP-MDK.md','CMSIS','The CMSIS-DAP MDK']
- ['Adv_Dev/Interface_Firmware.md','CMSIS','CMSIS-DAP Interface Firmware']
- ['Community/Intro.md','The mbed Community','The mbed Community']
- ['Community/Cont_SDK_HDK.md','The mbed Community','Contributing']
- ['Community/Collab.md','The mbed Community','Collaboration']
- ['Community/Edu.md','The mbed Community','Education']