site_name: mbed_v2_Handbook

pages:
- ['index.md','Introduction to Version 2']
- ['1_Getting_Started/1_Intro.md', 'Getting Started', 'Intro to mbed']
- ['1_Getting_Started/2_Plat_Comp_Intro.md', 'Getting Started','Platforms and Components']
- ['1_Getting_Started/3_User_Plat_Reg.md','Getting Started', 'User and Platform Registration']
- ['1_Getting_Started/4_IDE_API.md','Getting Started', 'The IDE and API']
- ['1_Getting_Started/5_First_Pro.md', 'Getting Started','First Program']
- ['2_Dev_Fun/1_Intro.md', 'Development Fundamentals', 'Intro to Development Fundamentals']
- ['2_Dev_Fun/3_old_SDK.md','Development Fundamentals', 'The SDK']
- ['2_Dev_Fun/2_API_Libs.md', 'Development Fundamentals','The APIs']
- ['2_Dev_Fun/2_API_Libs_Breakdown.md', 'Development Fundamentals','API Breakdown']
- ['2_Dev_Fun/4_HDK.md', 'Development Fundamentals','The HDK']
- ['3_Adv_Dev/1_Intro.md','Advanced Development', 'Advanced Development on mbed']
- ['3_Adv_Dev/2_Write_Publish.md','Advanced Development','Writing and Publishing Code']
- ['3_Adv_Dev/2_Coding_Style.md','Advanced Development','Coding Style Guide']
- ['3_Adv_Dev/3_Debug.md','Advanced Development','Debugging Code']
- ['3_Adv_Dev/4_Docu.md','Advanced Development','Documenting Code']
- ['3_Adv_Dev/5_Export.md','Advanced Development','Exporting Code']
- ['4_Community/1_Intro.md','The mbed Community','The mbed Community']
- ['4_Community/2_Questions.md','The mbed Community','Where to Ask Questions']
- ['4_Community/3_Cont_SDK_HDK.md','The mbed Community','Cont SDK HDK']
- ['4_Community/4_Edu.md','The mbed Community','Education']