site_name: mbed v2 Handbook

pages:
- ['index.md','Introduction to Version 2']
- ['1_Getting_Started/1_Intro.md','Introduction', 'Intro to mbed']
- ['1_Getting_Started/2_Plat_Comp_Intro.md','Introduction','Platforms and Components']
- ['1_Getting_Started/2_IDE_API.md','Introduction','The IDE and API']
- ['2_Dev_Fun/3_SDK.md','Introduction','The SDK']
- ['2_Dev_Fun/4_HDK.md','Introduction','The HDK']
- ['2_Dev_Fun/2_API_Libs.md','Introduction','The APIs']
- ['1_Getting_Started/3_User_Plat_Reg.md','Getting Started','User and Platform Registration']
- ['1_Getting_Started/4_Using_IDE.md','Getting Started','Using the Compiler']
- ['1_Getting_Started/5_First_Pro.md','Getting Started','First Program']
- ['2_Dev_Fun/1_Intro.md','Development Fundamentals','Intro to Development Fundamentals']
- ['2_Dev_Fun/2_API_Libs_Breakdown.md', 'Development Fundamentals','API Breakdown']
- ['2_Dev_Fun/4_CMSIS.md','Development Fundamentals','The CMSIS-DAP']
- ['3_Adv_Dev/1_Intro.md','Advanced Development','Advanced Development on mbed']
- ['3_Adv_Dev/1_PC_Com.md','Advanced Development','PC Serial Communication']
- ['3_Adv_Dev/2_Write_Publish.md','Advanced Development','Writing and Publishing Code']
- ['3_Adv_Dev/2_Coding_Style.md','Advanced Development','Coding Style Guide']
- ['3_Adv_Dev/3_Debug.md','Advanced Development','Debugging Code']
- ['3_Adv_Dev/4_Docu.md','Advanced Development','API Documentation']
- ['3_Adv_Dev/5_Export.md','Advanced Development','Offline Toolchains']
- ['4_Community/1_Intro.md','The mbed Community','The mbed Community']
- ['4_Community/2_Questions.md','The mbed Community','Where to Ask Questions']
- ['4_Community/3_Cont_SDK_HDK.md','The mbed Community','Contributing']
- ['4_Community/4_Edu.md','The mbed Community','Education']